name: Build and Test CIETools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install build dependencies
        run: pip install setuptools wheel

      - name: Set up QEMU (cross compile arm64 on linux)
        if: matrix.arch == 'arm64' && matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static

      - name: Set up macOS-specific compile flags
        if: matrix.os == 'macos-latest'
        run: |
          if [ "${{ matrix.arch }}" == "arm64" ]; then
            export EXTRA_COMPILE_ARGS="-target arm64-apple-macos11 -O3 -ffast-math"
          else
            export EXTRA_COMPILE_ARGS="-target x86_64-apple-macos11 -O3 -ffast-math"
          fi
        shell: bash

      - name: Build wheel
        run: python setup.py bdist_wheel
        env:
          EXTRA_COMPILE_ARGS: ${{ env.EXTRA_COMPILE_ARGS }}

      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          name: cietools-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/*.whl

      - name: Install the built wheel on Unix
        if: runner.os != 'Windows'
        run: pip install dist/*.whl

      - name: Install the built wheel on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: pip install (Get-ChildItem dist\*.whl).FullName

      - name: Run tests
        run: python -m unittest discover -s src/tests -p "*.py"